version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/webhook-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/kafka-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/amqp-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/nats-gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/http-executor"
    schedule:
      interval: "weekly"
