apiVersion: v1
kind: Service
metadata:
  name: bench-mockoon
  namespace: kubezap-bench
  labels:
    app.kubernetes.io/part-of: execution-latency-benchmark
spec:
  selector:
    app: bench-mockoon
  ports:
    - name: mock
      port: 3000
      targetPort: 3000
