---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.kubezap.io
  resources:
  - flowruns
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automation.kubezap.io
  resources:
  - flowruns/finalizers
  - triggers/finalizers
  verbs:
  - update
- apiGroups:
  - automation.kubezap.io
  resources:
  - flowruns/status
  - flows/status
  - triggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - automation.kubezap.io
  resources:
  - flows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
