---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - automation.kubezap.io
  resources:
  - flowruns
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - automation.kubezap.io
  resources:
  - flowruns/finalizers
  - triggers/finalizers
  verbs:
  - update
- apiGroups:
  - automation.kubezap.io
  resources:
  - flowruns/status
  - flows/status
  - integrations/status
  - webhookgatewayconfigs/status
  verbs:
  - get
  - update
- apiGroups:
  - automation.kubezap.io
  resources:
  - flows
  - integrations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - automation.kubezap.io
  resources:
  - triggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - automation.kubezap.io
  resources:
  - webhookgatewayconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
