apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubezap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "kubezap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      {{- include "kubezap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        control-plane: controller-manager
        {{- include "kubezap.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kubezap.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - --leader-elect={{ .Values.leaderElect }}
            - --health-probe-bind-address={{ .Values.healthProbeBindAddress }}
          env:
            - name: WEBHOOK_GATEWAY_IMAGE
              value: {{ .Values.gatewayImages.webhook | quote }}
            - name: KAFKA_GATEWAY_IMAGE
              value: {{ .Values.gatewayImages.kafka | quote }}
            - name: AMQP_GATEWAY_IMAGE
              value: {{ .Values.gatewayImages.amqp | quote }}
            - name: NATS_GATEWAY_IMAGE
              value: {{ .Values.gatewayImages.nats | quote }}
            {{- if .Values.watchNamespaces }}
            - name: WATCH_NAMESPACES
              value: {{ .Values.watchNamespaces | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
