{{- if include "kubezap.namespacedRBAC" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubezap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubezap.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubezap.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubezap.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
