/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package webhook contains admission webhook handlers for KubeZap CRDs.
package webhook

import (
	"context"
	"encoding/json"
	"net/http"

	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	automationv1alpha1 "github.com/kubezap/kubezap-operator/api/v1alpha1"
)

// FlowRunValidator validates FlowRun objects on admission.
type FlowRunValidator struct {
	decoder admission.Decoder
}

// Handle implements admission.Handler.
//
// It rejects FlowRun create and update requests where spec.flowRef.namespace is
// non-empty. Cross-namespace FlowRefs are not supported in v1alpha1; the feature
// is deferred to v1beta1 behind a FlowGrant CRD.
func (v *FlowRunValidator) Handle(ctx context.Context, req admission.Request) admission.Response {
	flowRun := &automationv1alpha1.FlowRun{}
	if err := v.decoder.DecodeRaw(req.Object, flowRun); err != nil {
		return admission.Errored(http.StatusBadRequest, err)
	}

	// FlowReference.Namespace was removed from the v1alpha1 API. Any object
	// that still carries the field (e.g., created against an older version of
	// the schema via a raw YAML apply) is rejected here.
	//
	// We check via the raw JSON rather than the decoded struct, because the Go
	// field no longer exists — a legacy client could still send the key.
	raw := map[string]interface{}{}
	if err := json.Unmarshal(req.Object.Raw, &raw); err != nil {
		return admission.Errored(http.StatusBadRequest, err)
	}

	if ns := extractFlowRefNamespace(raw); ns != "" {
		return admission.Denied(
			"cross-namespace FlowRef is not supported; FlowRef.Namespace must be empty " +
				"(cross-namespace flows deferred to v1beta1 with FlowGrant CRD)",
		)
	}

	return admission.Allowed("")
}

// InjectDecoder satisfies the admission.DecoderInjector interface used by
// controller-runtime to inject the webhook decoder.
func (v *FlowRunValidator) InjectDecoder(d admission.Decoder) error {
	v.decoder = d
	return nil
}

// extractFlowRefNamespace navigates the raw object JSON and returns the value
// of spec.flowRef.namespace, or an empty string if the key is absent or null.
func extractFlowRefNamespace(raw map[string]interface{}) string {
	spec, ok := raw["spec"].(map[string]interface{})
	if !ok {
		return ""
	}
	flowRef, ok := spec["flowRef"].(map[string]interface{})
	if !ok {
		return ""
	}
	ns, _ := flowRef["namespace"].(string)
	return ns
}

// SetupFlowRunWebhook registers the FlowRun validating webhook with the
// controller-manager's webhook server.
//
// The wiring step in cmd/main.go should call this function after building the
// manager, passing the same ctrl.Manager used for controllers.
//
// The webhook path matches the convention generated by kubebuilder for
// automation.kubezap.io/v1alpha1/FlowRun:
//
//	/validate-automation-kubezap-io-v1alpha1-flowrun
func SetupFlowRunWebhook(mgr ctrl.Manager) error {
	mgr.GetWebhookServer().Register(
		"/validate-automation-kubezap-io-v1alpha1-flowrun",
		&admission.Webhook{
			Handler: &FlowRunValidator{},
		},
	)
	return nil
}
