/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package webhook

import (
	"context"
	"fmt"
	"net/http"

	admissionv1 "k8s.io/api/admission/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	automationv1alpha1 "github.com/kubezap/kubezap-operator/api/v1alpha1"
)

// +kubebuilder:rbac:groups=automation.kubezap.io,resources=webhookgatewayconfigs,verbs=get;list;watch

// WebhookGatewayConfigValidator enforces the WebhookGatewayConfig singleton-per-namespace
// invariant: at most one WebhookGatewayConfig object may exist per namespace, regardless of
// name. See docs/design/2026-09-12-webhookgatewayconfig-crd.md, Rejected Alternative A, for
// why this is an admission-time rejection rather than a fixed required object name.
type WebhookGatewayConfigValidator struct {
	Client  client.Client
	decoder admission.Decoder
}

// Handle implements admission.Handler.
//
// It rejects a WebhookGatewayConfig create request when the incoming object's namespace
// already contains another WebhookGatewayConfig (any name). Update and delete requests are
// always allowed — the singleton rule only needs to guard the moment a second object would
// come into existence.
func (v *WebhookGatewayConfigValidator) Handle(ctx context.Context, req admission.Request) admission.Response {
	if req.Operation != admissionv1.Create {
		return admission.Allowed("")
	}

	cfg := &automationv1alpha1.WebhookGatewayConfig{}
	if err := v.decoder.Decode(req, cfg); err != nil {
		return admission.Errored(http.StatusBadRequest, err)
	}

	var existing automationv1alpha1.WebhookGatewayConfigList
	if err := v.Client.List(ctx, &existing, client.InNamespace(cfg.Namespace)); err != nil {
		return admission.Errored(http.StatusInternalServerError, err)
	}

	if len(existing.Items) > 0 {
		return admission.Denied(fmt.Sprintf(
			"namespace %q already has a WebhookGatewayConfig named %q — at most one "+
				"WebhookGatewayConfig is allowed per namespace",
			cfg.Namespace, existing.Items[0].Name,
		))
	}

	return admission.Allowed("")
}

// +kubebuilder:webhook:path=/validate-automation-kubezap-io-v1alpha1-webhookgatewayconfig,mutating=false,failurePolicy=fail,sideEffects=None,groups=automation.kubezap.io,resources=webhookgatewayconfigs,verbs=create,versions=v1alpha1,name=vwebhookgatewayconfig.kb.io,admissionReviewVersions=v1

// SetupWebhookGatewayConfigWebhook registers the WebhookGatewayConfig singleton-enforcing
// validating webhook with the controller-manager's webhook server.
//
// The wiring step in cmd/main.go should call this function after building the manager,
// passing the same ctrl.Manager used for controllers — mgr.GetClient() supplies the Client
// field, mirroring how reconcilers are constructed in cmd/main.go.
//
// The webhook path matches the convention generated by kubebuilder for
// automation.kubezap.io/v1alpha1/WebhookGatewayConfig:
//
//	/validate-automation-kubezap-io-v1alpha1-webhookgatewayconfig
//
// NOTE: this +kubebuilder:webhook marker must stay free-floating (its own comment
// block, blank line before this doc comment) — per this project's documented
// controller-gen gotcha (see CLAUDE.md), a package-scoped marker attached directly to a
// declaration's doc comment is silently dropped by controller-gen, with no error.
func SetupWebhookGatewayConfigWebhook(mgr ctrl.Manager) error {
	decoder := admission.NewDecoder(mgr.GetScheme())
	mgr.GetWebhookServer().Register(
		"/validate-automation-kubezap-io-v1alpha1-webhookgatewayconfig",
		&admission.Webhook{
			Handler: &WebhookGatewayConfigValidator{
				Client:  mgr.GetClient(),
				decoder: decoder,
			},
		},
	)
	return nil
}
