apiVersion: automation.kubezap.io/v1alpha1
kind: Trigger
metadata:
  name: pod-failure-watcher
  namespace: default
spec:
  type: resource
  resource:
    apiVersion: v1
    kind: Pod
    namespace: default
    labelSelector:
      matchLabels:
        app: my-service
    events: [create, update]
    watchFields:
      - ".status.phase"
  flowRef:
    name: handle-pod-event
