apiVersion: automation.kubezap.io/v1alpha1
kind: Trigger
metadata:
  labels:
    app.kubernetes.io/name: kubezap
    app.kubernetes.io/managed-by: kustomize
  name: nats-orders
  namespace: default
spec:
  type: nats
  enabled: true
  nats:
    integrationRef:
      name: my-nats
    subject: orders.created
  flowRef:
    name: process-order
