## Append samples of your project ##
resources:
- automation_v1alpha1_trigger.yaml
- automation_v1alpha1_flow.yaml
- automation_v1alpha1_flowrun.yaml
- automation_v1alpha1_integration.yaml
- automation_v1alpha1_integration_http.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
